# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Costa Rica
author: Nicholas Coronado and Julie Allen
author_link: https://whatever.you/like
author_description: A good traveller has no fixed plans and is not intent on arriving.
email: ncoronado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is here to share our experiences and lessons learned from traveling the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trekkingpenguins.com" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: true

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
